### ISSUE TITLE
[QUESTION] CO2 simulation got negative value and crash, but re-run was success

### ISSUE THREAD

**Issue by hgrhgy** [geoschem/geos-chem#1081]
### Ask a question about GEOS-Chem:

GCClassic CO2 simulation crash because of the negative co2 concentration.  After the crash, re-run the simlution again was success. 

VERSION:
- GCClassic version: 13.3.4
- GEOS-Chem version: 13.3.4
- HEMCO version: 3.3.0
- 

[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/7811512/HISTORY.rc.txt)
[input.geos.txt](https://github.com/geoschem/geos-chem/files/7811513/input.geos.txt)
[run.log.txt](https://github.com/geoschem/geos-chem/files/7811514/run.log.txt)
[run.log.error.txt](https://github.com/geoschem/geos-chem/files/7811515/run.log.error.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/7811516/HEMCO_Config.rc.txt)

```log
UCX (SFCMR_READ): Opening /share/nfs1_share1/GEOSCHEM_DATA/CHEM_INPUTS/UCX_201403/NoonTime/Grid2x25/InitCFC_JNO2_12.dat
UCX (SFCMR_READ): Opening /share/nfs1_share1/GEOSCHEM_DATA/CHEM_INPUTS/UCX_201403/NoonTime/Grid2x25/InitCFC_JNO3_12.dat
UCX (SFCMR_READ): Opening /share/nfs1_share1/GEOSCHEM_DATA/CHEM_INPUTS/UCX_201403/NoonTime/Grid2x25/InitCFC_JN2O_12.dat

********************************************
* B e g i n   T i m e   S t e p p i n g !! *
********************************************

---> DATE: 2019/07/01  UTC: 00:00  X-HRS:      0.000000
 HEMCO already called for this timestep. Returning.
===============================================================================
TPCORE_FVDAS (based on GMI) Tracer Transport Module successfully initialized
===============================================================================
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507         223          10
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507         109          28
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507         337          40
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507         128          33
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507         242          15
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507         318          35
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507          14          12
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507          14          13
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507          14          14
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507          14          15
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507          14          16
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507          14          17
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507          14          18
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507          14          19
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507          14          20
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507          14          21
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507          14          22
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507          14          23
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507          14          24
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507          14          25
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507          14          26
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507          14          27
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507          14          28
 WARNING: Negative concentration for species CO2 at (I,J,L) =          507          14          29
...etc...
===============================================================================
GEOS-Chem ERROR:
 -> at DO_TEND (in module GeosCore/mixing_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountred in "DO_TEND"!
 -> at DO_MIXING (in module GeosCore/mixing_mod.F90)
===============================================================================

===============================================================================
GEOS-CHEM ERROR: Error encountered in "Do_Mixing"!
STOP at  -> at GEOS-Chem (in GeosCore/main.F90)
===============================================================================

```

**Comment by yantosca** [comment]
Thanks for writing @hgrhgy.  I believe this may be caused when routine `INIT_UCX` is getting called.  But `INIT_UCX` is only needed for the fullchem simulations.  This was a bug, which was fixed in commit https://github.com/geoschem/geos-chem/commit/0d2b8eaea9ae26c159b99083fb2382d017c48d2c.  This will go into 13.4.0.

In the meantime, you can add this IF statement at the top of routine `INIT_UCX` (in `GeosCore/ucx_mod.F90`) that will cause `INIT_UCX` to exit unless it is either a fullchem or aerosol-only simulation:

https://github.com/geoschem/geos-chem/blob/a07bd3a9b387c51d98ed14ae7ee7def67e8bec98/GeosCore/ucx_mod.F90#L4356-L4363

**Comment by hgrhgy** [comment]
Thanks for reply @yantosca . 
After adding the IF statement, the problem is not solved.
Is there any other code that needs to be added.

**Comment by hgrhgy** [comment]
I update the version 13.4.0-alpha.12, and add the IF statement. The probelm is still not solved.
The running logs are attached. 
[run.log.error.txt](https://github.com/geoschem/geos-chem/files/7836911/run.log.error.txt)
[run.log.txt](https://github.com/geoschem/geos-chem/files/7836912/run.log.txt)

**Comment by yantosca** [comment]
@hgrhgy, I would also recommend recompiling and running with the compiler debug flags.  In your run directory:

```console
$ mkdir build_debug
$ cd build_debug
$ cmake ../CodeDir -DRUNDIR=.. -DCMAKE_BUILD_TYPE=Debug
$ make -j
$ make -j install
$ cd ..
$ ./gcclassic > GC.log
```
and then see if that picks up any errors.

**Comment by hgrhgy** [comment]
I re-build the gcclassic and set `Turn on debug printout? : T` in input.geos. the log is attached.
and the CO2 min/max values in rst file are positive.
```
Python 3.7.11 (default, Jul 27 2021, 14:32:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xarray as xr
>>> ds = xr.open_dataset('GEOSChem.Restart.20190701_0600z.nc4')
>>> ds.SpeciesRst_CO2
<xarray.DataArray 'SpeciesRst_CO2' (time: 1, lev: 47, lat: 361, lon: 576)>
[9772992 values with dtype=float32]
Coordinates:
  * time     (time) datetime64[ns] 2019-07-01T06:00:00
  * lev      (lev) float64 0.9925 0.9775 0.9625 ... 0.0004141 0.0001387 3.8e-05
  * lat      (lat) float64 -89.88 -89.5 -89.0 -88.5 ... 88.5 89.0 89.5 89.88
  * lon      (lon) float64 -180.0 -179.4 -178.8 -178.1 ... 178.1 178.8 179.4
Attributes:
    long_name:         Dry mixing ratio of species CO2
    units:             mol mol-1 dry
    averaging_method:  instantaneous
>>> ds.SpeciesRst_CO2.min()
<xarray.DataArray 'SpeciesRst_CO2' ()>
array(0.0003527)
>>> ds.SpeciesRst_CO2.max()
<xarray.DataArray 'SpeciesRst_CO2' ()>
array(0.00048298)
>>> 

```
[run.log.error.txt](https://github.com/geoschem/geos-chem/files/7844135/run.log.error.txt)
