### ISSUE TITLE
[BUG/ISSUE] Seg fault when enabling ProdLoss diagnostic collection in 14.0.0-rc.0

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#1287]
When enabling the ProdLoss diagnostic collection for the 10-year benchmark simulation in GEOS-Chem Classic 14.0.0-rc.0, we encounter a segmentation fault:

```
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#1  0x478da6 in __fullchem_mod_MOD_do_fullchem._omp_fn.1
	at /n/home05/msulprizio/BM/10yr/14.0.0-rc.0/GCClassic/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:1319
#2  0x2b431a1119e5 in gomp_thread_start
#3  0x2b431a79cea4 in ???
#4  0x2b431aaaf9fc in ???
	at ../.././libgomp/team.c:123
#5  0xffffffffffffffff in ???
```

which can be traced to this code:

https://github.com/geoschem/geos-chem/blob/c709270c57bb6f924f414007f45810355e5f8afd/GeosCore/fullchem_mod.F90#L1315-L1321

**Comment by msulprizio** [comment]
This should now be fixed in commit https://github.com/geoschem/geos-chem/commit/b4385319d35ae802d12c1e7b5deb56edaaef27a5 (currently in the `release` branch)

**Comment by msulprizio** [comment]
The commit above did not resolve this issue after all. There may be a problem with the use of the wildcard in the ProdLoss diagnostic now. When enabling debug printout, the GEOS-Chem log file does not list all expected species for that collection:

```
 Loss_?LOS?
    state:      DIAG
    metadataID: LOSS
    registryID: LOSS
    isWildcard:  T
    wildcard:   LOS

 Prod_?PRD?
    state:      DIAG
    metadataID: PROD
    registryID: PROD
    isWildcard:  T
    wildcard:   PRD

...

PROD
  numWildCards:    1
                     PRD    1

LOSS
  numWildCards:    1
                     LOS    1

...

 ------------------------------------------------------------------------------
 Container Name   : ProdLoss
 Container Id #   :              12
 nX               :              72
 nY               :              46
 nZ               :              72
 nB               :               2
 EpochJsec        :    212129064000.0
 EpochJd          :         2455197.5
 CurrentJSec      :    212129064000.0
 CurrentJd        :         2455197.5
 CurrentYmd       :        20100101
 CurrentHms       :          000000
 ElapsedSec       :               0.0
 UpdateMode       : time-averaged
 UpdateYmd        :        00000000
 UpdateHms        :          001000
 UpdateIvalSec    :             600.0
 UpdateAlarm      :             600.0
 Operation        : Accumulate from source
 HeartBeatDtSec   :             600.0
 ReferenceYmd     :        20100101
 ReferenceHms     :          000000
 ReferenceJsec    :         2455197.5
 ReferenceJd      :         2455197.5
 FileWriteYmd     :        00000100
 FileWriteHms     :          000000
 FileWriteIvalSec :         2678400.0
 FileWriteAlarm   :         2678400.0
 FileCloseYmd     :        00000100
 FileCloseHms     :          000000
 FileCloseIvalSec :         2678400.0
 FileCloseAlarm   :         2678400.0
 CurrTimeSlice    :            -999
 IsFileOpen       :               F
 IsFileDefined    :               F
 FileId           :            -999
 xDimId           :            -999
 yDimId           :            -999
 zDimId           :            -999
 tDimId           :            -999
 bDimId           :            -999
 FileExpId        : OutputDir/GEOSChem
 FilePrefix       : OutputDir/GEOSChem.ProdLoss.
 FileTemplate     : %y4%m2%d2_%h2%n2z.nc4
 Filename         : OutputDir/GEOSChem.ProdLoss.%y4%m2%d2_%h2%n2z.nc4
 Conventions      : COARDS
 NcFormat         : not found
 History          : 
 ProdDateTime     : 
 Reference        : www.geos-chem.org; wiki.geos-chem.org
 Title            : GEOS-Chem diagnostic collection: ProdLoss
 Contact          : GEOS-Chem Support Team (geos-chem-support@g.harvard.edu)
 StartTimeStamp   : 2010-01-01 00:00:00z
 EndTimeStamp     : 2010-02-01 00:00:00z
 
 Items archived in this collection:
  ProdCOfromNMVOC      | Porduction of CO by NMVOC           | xyz | molec cm-3 s-1
  ProdCOfromCH4        | Production of CO by CH4             | xyz | molec cm-3 s-1
  LossHNO3onSeaSalt    | Loss of HNO3 on sea salt aerosols   | xyz | kg s-1
  Loss_CH4             | Chemical loss of CH4                | xyz | molec cm-3 s-1
  Loss_CO              | Chemical loss of CO                 | xyz | molec cm-3 s-1
  Loss_Ox              | Chemical loss of Ox                 | xyz | molec cm-3 s-1
  ProdSO4fromO3s       | Production of SO4 from O3s          | xyz | kg S s-1
  ProdSO4fromSRHObr    | Production of SO4 from SRHOBr       | xyz | kg S s-1
  ProdSO4fromSRO3      | Production of SO4 by SRO3           | xyz | kg S s-1
  ProdSO4fromHOBrInClo | Production of SO4 from aqueous oxid | xyz | kg S s-1
  ProdSO4fromO3inSeaSa | Production of SO4 from O3 in sea sa | xyz | kg S s-1
  ProdSO4fromO3inCloud | Production of SO4 from aqueous oxid | xyz | kg S s-1
  ProdSO4fromO2inCloud | Production of SO4 from aqueous oxid | xyz | kg S
  ProdSO4fromH2O2inClo | Production of SO4 from aqueous oxid | xyz | kg S s-1
  ProdSO4fromHMSinClou | Production of SO4 from aqueous oxid | xyz | kg S s-1
  ProdSO2andHCHOfromHM | Production of SO2 and HCHO from aqu | xyz | kg S s-1
  ProdHMSfromSO2andHCH | Production of HMS from aqueous reac | xyz | kg S s-1
  ProdOCPIfromOCPO     | Production of hydrophilic organic c | xyz | kg
  ProdBCPIfromBCPO     | Production of hydrophilic black car | xyz | kg
  Prod_H2O2            | Chemical production of H2O2         | xyz | molec cm-3 s-1
  Prod_SO4             | Chemical production of SO4          | xyz | molec cm-3 s-1
  Prod_CO              | Chemical production of CO           | xyz | molec cm-3 s-1
  Prod_Ox              | Chemical production of Ox           | xyz | molec cm-3 s-1
 ------------------------------------------------------------------------------

...


```

**Comment by yantosca** [comment]
I ran a 1-hr simulation with this fix and the following data variables were written to the ProdLoss collection file:
```console
float AREA(lat, lon) ;
float ProdCOfromNMVOC(time, lev, lat, lon) ;
float ProdCOfromCH4(time, lev, lat, lon) ;
float LossHNO3onSeaSalt(time, lev, lat, lon) ;
float Loss_CH4(time, lev, lat, lon) ;
float Loss_CO(time, lev, lat, lon) ;
float Loss_Ox(time, lev, lat, lon) ;
float ProdSO4fromO3s(time, lev, lat, lon) ;
float ProdSO4fromSRHObr(time, lev, lat, lon) ;
float ProdSO4fromSRO3(time, lev, lat, lon) ;
float ProdSO4fromHOBrInCloud(time, lev, lat, lon) ;
float ProdSO4fromO3inSeaSalt(time, lev, lat, lon) ;
float ProdSO4fromO3inCloud(time, lev, lat, lon) ;
float ProdSO4fromO2inCloudMetal(time, lev, lat, lon) ;
float ProdSO4fromH2O2inCloud(time, lev, lat, lon) ;
float ProdSO4fromHMSinCloud(time, lev, lat, lon) ;
float ProdSO2andHCHOfromHMSinCloud(time, lev, lat, lon) ;
float ProdHMSfromSO2andHCHOinCloud(time, lev, lat, lon) ;
float ProdOCPIfromOCPO(time, lev, lat, lon) ;
float ProdBCPIfromBCPO(time, lev, lat, lon) ;
float Prod_H2O2(time, lev, lat, lon) ;
float Prod_SO4(time, lev, lat, lon) ;
float Prod_CO(time, lev, lat, lon) ;
float Prod_Ox(time, lev, lat, lon) ;
```
@msulprizio: How is the error still manifesting itself?
