### ISSUE TITLE
GFED 2020 Jan & Feb file errors

### ISSUE THREAD

**Issue by Haihui-Zhu** [geoschem/geos-chem#2808]
### Your name

Haihui Zhu

### Your affiliation

Colorado State University

### What happened? What did you expect to happen?

The following two files downloaded from http://geoschemdata.wustl.edu/ have different time stamp errors:
v2023-03/2020/GFED4_dailyfrac_gen.025x025.202001.nc 
v2023-03/2020/GFED4_dailyfrac_gen.025x025.202002.nc 

The time stamp for 202001 looks like:
```
 time = 0, 1, 2, 3, 4, 5, 0.0078125, 0.0078125, 0.0078125, 0.0078125, 
    0.0078125, 0.0078125, 0.0078125, 0.0078125, 0.0078125, 0.0078125, 
    0.0078125, 0.0078125, 0.0078125, 0.0078125, 0.0078125, 0.0078125, 
    0.0078125, 0.0078125, 0.0078125, 0.0078125, 0.0078125, 0.0078125, 
    0.0078125, 0.0078125, 0.0078125 
```

The 202002 file has only 28 days while it is a leap year. 

Fortunately the March file is correctly starting from the 60th day. 

### What are the steps to reproduce the bug?

Go to ExtData/HEMCO/GFED4/v2023-03/2020/ on any data portal. I only looked at the WashU portal. Not sure about the others. 

### What GEOS-Chem version were you using?

14.4.1

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

gcc 9.4.2

### Will you be addressing this bug yourself?

Yes

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

4x5

### What meterology fields did you use?

GEOS-FP

**Comment by yantosca** [comment]
Thanks for letting us know @Haihui-Zhu.  I can fix the files and push them over.

**Comment by yantosca** [comment]
@Haihui-Zhu @yuyao-cyber, I've pushed fixed files over to WashU via Globus.  Bill, could you check if the file permissions are OK?

**Comment by yuyao-cyber** [comment]
@yantosca @Haihui-Zhu The files are ready up there. Thanks!

**Comment by nicodgomez** [comment]
Hi, I believe there's still an error in the GFED4_dailyfrac_gen.025x025.202002.nc file from the Washu portal. I downloaded it from that portal, and when I open it, it specifies a time attribute of 28 days, when it should be 29.

_<xarray.Dataset>
Dimensions:       (lat: 720, lon: 1440, time: 28)
Coordinates:
  * time          (time) datetime64[ns] 2020-02-01 2020-02-02 ... 2020-02-28
  * lon           (lon) float32 -179.9 -179.6 -179.4 ... 179.4 179.6 179.9
  * lat           (lat) float32 -89.88 -89.62 -89.38 ... 89.38 89.62 89.88
Data variables:
    GFED_FRACDAY  (time, lat, lon) float32 ...
Attributes:
    CDI:          Climate Data Interface version 1.9.4 (http://mpimet.mpg.de/...
    Conventions:  CF-1.6
    CDO:          Climate Data Operators version 1.9.4 (http://mpimet.mpg.de/...
    conventions:  COARDS
    title:        GFED daily emission fractions
    history:      Fri Jan 27 13:29:52 2023: ncatted -a units,GFED_FRACDAY,c,c...
    NCO:          netCDF Operators version 4.7.4 (http://nco.sf.net)_

**Comment by yantosca** [comment]
Thanks @nicodgomez, I'll remove the stale tag.

You are right, there are only 28 days.  I checked the GFED_FRACDAY data for 2012 (another leap year) and there are 29 time slices.  

```console
netcdf GFED4_dailyfrac_gen.025x025.201202 {
dimensions:
        time = UNLIMITED ; // (29 currently)
        lon = 1440 ;
        lat = 720 ;
... etc ...
 time = "2012-02-01", "2012-02-02", "2012-02-03", "2012-02-04", "2012-02-05", 
    "2012-02-06", "2012-02-07", "2012-02-08", "2012-02-09", "2012-02-10", 
    "2012-02-11", "2012-02-12", "2012-02-13", "2012-02-14", "2012-02-15", 
    "2012-02-16", "2012-02-17", "2012-02-18", "2012-02-19", "2012-02-20", 
    "2012-02-21", "2012-02-22", "2012-02-23", "2012-02-24", "2012-02-25", 
    "2012-02-26", "2012-02-27", "2012-02-28", "2012-02-29" ;
```

**Comment by yantosca** [comment]
@nicodgomez I will open a new issue for this and close out this issue. as the original problem of @Haihui-Zhu has been solved.
