### ISSUE TITLE
[QUESTION] How to compile GEOS-Chem with specific chemistry mechanism

### ISSUE THREAD

**Issue by xpye98** [geoschem/geos-chem#470]
# Ask a question about GEOS-Chem:

Hi, 

I'm using GEOS-Chem 12.9.3 and cmake to compile it.
Following [FlexChem](http://wiki.seas.harvard.edu/geos-chem/index.php/FlexChem), I've set up my custom KPP, but I don't know how to compile GEOS-Chem using new custom chemistry mechanism. 
Wiki says "Compile GEOS-Chem for the new mechanism by including CHEM=Custom in your make command.", but I found it of no use. (or maybe I misunderstood it). Now I just rename `KPP/Custom` to `KPP/Tropchem`, it works, but sometimes I just have to run different chemistry mechanism at the same time.

Thanks,
Xingpei

**Comment by msulprizio** [comment]
Thanks for writing. The `make CHEM=Custom` command was implemented as a GNU Make feature. When CMake was added, options for the KPP Standard, Tropchem and SOA_SVPOA chem were added but not Custom. This has been fixed our dev/13.0.0 branch (with the [retiring of the tropchem mechanism](https://github.com/geoschem/geos-chem/issues/332)). Modifications that were needed included adding lines for the Custom mechanism in the following files. In GeosCore/CMakeLists.txt:

```
# Add dependency on the correct KPP library
		$<$<STREQUAL:${MECH},SOA_SVPOA>:KPP_SOA_SVPOA>
		$<$<STREQUAL:${MECH},Standard>:KPP_Standard>
		$<$<STREQUAL:${MECH},Tropchem>:KPP_Tropchem>
		$<$<STREQUAL:${MECH},Custom>:KPP_Custom>
```

and in KPP/CMakeLists.txt:

```
add_subdirectory(Standard)
add_subdirectory(Tropchem)
add_subdirectory(SOA_SVPOA)
add_subdirectory(Custom)
```

That will tell the compiler to include the KPP/Custom subdirectory when compiling GEOS-Chem. Then you can navigate to your build directory and type `cmake [CODEDIR] -DMECH=Custom` and recompile from there.

**Comment by xpye98** [comment]
Thanks for responding, Melissa.
I followed your guide, but there is still an error when doing `cmake [CODEDIR] -DMECH=Custom`. The error says:

CMake Error at CMakeScripts/GC-ConfigureClassic.cmake:172 (message):
  The value of MECH, "custom", is an invalid chemistry mechanism! Select one
  of: Standard;Tropchem;SOA_SVPOA.

It seems like I need to edit something in `CMakeScripts/GC-ConfigureClassic.cmake`

**Comment by xpye98** [comment]
Thanks!

I noticed that in `Headers/CmakeLists.txt`, we also need to add line like this
 `$<$<STREQUAL:${MECH},Custom>:KPP_Custom>`
to let cmake know the Custom KPP directory.

After that, the compile will succeed.

**Comment by msulprizio** [comment]
Excellent! Glad you got it working. I will close out the issue for now, but feel free to reopen if anything else comes up.
